### PR TITLE
Render server-side with phantom.js

### PR DESCRIPTION
**Pull request by arlolra**
Initial implementation. Still some work to be done.

Not very performant, but it does address a need:
https://lists.torproject.org/pipermail/tor-talk/2013-December/031494.html

### CODE REVIEW

**Comment by makepanic** [comment]
Thanks

Do you think this is a better approach than rewriting globe with something like expressjs?

I'm currently working on https://github.com/makepanic/globe-node/tree/develop that uses [express](http://expressjs.com/) and some parts of the current globe to fix this issue.

**Comment by arlolra** [comment]
> Do you think this is a better approach than rewriting globe with something like expressjs?

I think the majority of traffic you'll get will have JavaScript enabled and this approach solves the problem with the least amount of effort. But don't let me discourage you if that's the route you'd prefer to go.

**Comment by arlolra** [comment]
Closing in favour of [globe-node](https://github.com/makepanic/globe-node).

**Comment by makepanic** [comment]
Thanks anyway!

**Pull request closed without merging**
